language: erlang
otp_release:
   - R14B04
   - R14B03
   - R14B02
   - R14B01
   - R14B
   - R14A
   - R13B04
   - R13B03
before_script:
  - sudo apt-get update
  - sudo apt-get -y install xulrunner-1.9.2-dev libicu-dev libcurl4-openssl-dev
  # the right way to do this would be:
  # - sudo "echo /usr/lib/xulrunner-1.9.2.24 >> /etc/ld.so.conf.d/xulrunner.conf"
  # - sudo "echo /usr/lib/xulrunner-devel-1.9.2.24" >> /etc/ld.so.conf.d/xulrunner.conf
  # - sudo /sbin/ldconfig
  # but that obviously doesn't work, so we do:
  - sudo ln -s /usr/lib/xulrunner-1.9.2.*/libmozjs.so /usr/lib/
  - ./bootstrap
  - ./configure
script:
  - make check
