before_install:
   - sudo apt-get -y update
   - sudo apt-get -y install libicu-dev libmozjs-dev pkg-config help2man
   - sudo apt-get -y install libtool automake autoconf autoconf-archive
   - sudo apt-get -y install texlive-latex-base texlive-latex-recommended
   - sudo apt-get -y install texlive-latex-extra texlive-fonts-recommended texinfo
   - sudo apt-get -y install python-pygments python-docutils python-sphinx 
before_script: ./bootstrap && ./configure
script: make distcheck
language: erlang
otp_release:
   - R15B02
   - R15B01
   - R15B
   - R14B04
   - R14B03
